/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id1.bmicalc;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Vonkhar
 */
public class mainFrame extends javax.swing.JFrame {

   

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bmiTF = new javax.swing.JTextField();
        wkgTF = new javax.swing.JTextField();
        hfTF = new javax.swing.JTextField();
        hiTF = new javax.swing.JTextField();
        clearBtn = new javax.swing.JButton();
        calculateBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BMI CALCULATOR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 10, 250, 32);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Weight in KG:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 180, 150, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Height in Feet:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 60, 130, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Height in Inches:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 120, 150, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("BMI:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 220, 80, 60);

        bmiTF.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        bmiTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bmiTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmiTFActionPerformed(evt);
            }
        });
        getContentPane().add(bmiTF);
        bmiTF.setBounds(160, 240, 140, 30);

        wkgTF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        wkgTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wkgTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wkgTFActionPerformed(evt);
            }
        });
        getContentPane().add(wkgTF);
        wkgTF.setBounds(190, 180, 100, 30);

        hfTF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hfTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hfTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hfTFActionPerformed(evt);
            }
        });
        getContentPane().add(hfTF);
        hfTF.setBounds(190, 60, 100, 30);

        hiTF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hiTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hiTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiTFActionPerformed(evt);
            }
        });
        getContentPane().add(hiTF);
        hiTF.setBounds(190, 120, 100, 30);

        clearBtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn);
        clearBtn.setBounds(220, 300, 120, 34);

        calculateBtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        calculateBtn.setText("Calculate");
        calculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(calculateBtn);
        calculateBtn.setBounds(60, 300, 120, 34);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bmiTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmiTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bmiTFActionPerformed

    private void wkgTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wkgTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wkgTFActionPerformed

    private void hfTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hfTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hfTFActionPerformed

    private void hiTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hiTFActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        hfTF.setText("");
        hiTF.setText("");
        wkgTF.setText("");
        bmiTF.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void calculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtnActionPerformed
        double bmi=0 ,hf, hi, hm,wkg;
        hf = Double.parseDouble(hfTF.getText());
        hi = Double.parseDouble(hiTF.getText());
        wkg = Double.parseDouble(wkgTF.getText());
        hm = ((hf*30.48) + (hi*2.54))/100;
        bmi = wkg/(Math.pow(hm,2));
        bmiTF.setText(""+String.format("%.2f", bmi));
    }//GEN-LAST:event_calculateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bmiTF;
    private javax.swing.JButton calculateBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextField hfTF;
    private javax.swing.JTextField hiTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField wkgTF;
    // End of variables declaration//GEN-END:variables

    
    
}
