/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

/**
 *
 * @author KuchiChai
 */
public class BankGUI extends javax.swing.JFrame {
    private double balance = 10000;
    /**
     * Creates new form BankGUI
     */
    public BankGUI() {
        initComponents();
    }
    
    public double getBalance()
    {
        return this.balance;
    }
    public void withdraw(double amount)
    {
        if(amount < 0)
        {
            System.out.println("Invalid Amount");
        }
        else 
        {
            if (amount > this.balance)
            {
                System.out.println("Insufficient funds");
            }
            else
            {
                if(amount%100 != 0)
                {
                    System.out.println("Cannot dispense bills. It can only dispense"
                            + " money that are divisible by 100");
                }
                else 
                {
                    this.balance = this.balance - amount;
                    System.out.println("Successful Transaction");
                }
                    
            }
        }
     }
    public void deposit(double amount)
    {
        if(amount < 0)
        {
            System.out.println("Invalid Amount");
        }
        else 
        {
            if (amount > this.balance)
            {
                System.out.println("Insufficient funds");
            }
            else
            {
                if(amount%100 != 0)
                {
                    System.out.println("Cannot add. It can only add"
                            + " money that are divisible by 100");
                }
                else 
                {
                    this.balance = this.balance + amount;
                    System.out.println("Successful Transaction");
                }
                    
            }
        }
     }
    public void fastcash(double amount){
        this.balance = this.balance - amount;
        System.out.println("Successful Transaction");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FCbtn = new javax.swing.JButton();
        BIbtn = new javax.swing.JButton();
        CPbtn = new javax.swing.JButton();
        Dbtn = new javax.swing.JButton();
        Wbtn = new javax.swing.JButton();
        Depbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));
        jPanel1.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SCAM BANK");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 40, 250, 60);

        FCbtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        FCbtn.setText("Fast Cash");
        FCbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FCbtnActionPerformed(evt);
            }
        });
        jPanel1.add(FCbtn);
        FCbtn.setBounds(340, 360, 190, 60);

        BIbtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BIbtn.setText("Balance Inquiry");
        BIbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIbtnActionPerformed(evt);
            }
        });
        jPanel1.add(BIbtn);
        BIbtn.setBounds(50, 170, 200, 60);

        CPbtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CPbtn.setText("Change PIN");
        jPanel1.add(CPbtn);
        CPbtn.setBounds(50, 260, 200, 60);

        Dbtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Dbtn.setText("Developer");
        jPanel1.add(Dbtn);
        Dbtn.setBounds(50, 360, 200, 60);

        Wbtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Wbtn.setText("Withdraw");
        Wbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Wbtn);
        Wbtn.setBounds(340, 170, 190, 60);

        Depbtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Depbtn.setText("Deposit");
        Depbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Depbtn);
        Depbtn.setBounds(340, 260, 190, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -10, 600, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BIbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIbtnActionPerformed
        new BalanceInquiry(BankGUI.this).setVisible(true);
    }//GEN-LAST:event_BIbtnActionPerformed

    private void WbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WbtnActionPerformed
        new Withdraw(BankGUI.this).setVisible(true);
    }//GEN-LAST:event_WbtnActionPerformed

    private void DepbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepbtnActionPerformed
        new Deposit(BankGUI.this).setVisible(true);
                
    }//GEN-LAST:event_DepbtnActionPerformed

    private void FCbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FCbtnActionPerformed
        new FastCash(BankGUI.this).setVisible(true);
    }//GEN-LAST:event_FCbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BIbtn;
    private javax.swing.JButton CPbtn;
    private javax.swing.JButton Dbtn;
    private javax.swing.JButton Depbtn;
    private javax.swing.JButton FCbtn;
    private javax.swing.JButton Wbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
